#!/usr/bin/env bash
set -e
# init - Initialize the container

cd /var/www
source vars

cp "/usr/share/zoneinfo/$tz" /etc/localtime
echo "$tz" >/etc/timezone

sed -i 's/upload_max_filesize = .*/upload_max_filesize = 10G/' /etc/php8/php.ini
sed -i 's/post_max_size = .*/post_max_size = 10G/' /etc/php8/php.ini

crond
line='SHELL=/bin/bash\n\n# Every minute\n* * * * *  /var/www/encode\n\n# Streams'
echo -e "$line" |crontab -

sed -i "s/%sslmail%/$sslmail/" /root/Caddyfile

[[ $interface ]] || interface=:80
sed -i "s/%interface%/$interface/" /root/Caddyfile

chmod +x /usr/bin/caddy /usr/bin/mailer

php-fpm8 -R
caddy start --config /root/Caddyfile --adapter caddyfile >caddy.log

sleep 9999d
