#!/usr/bin/env bash

# stream - Stream video when called from crontab
# Usage:  stream <tag>
#   The tag refers to video files in ./uploadpage/streams without the
#   '.mp4', that should have been re-encoded by `encode`. The tag has no path
#   information, has the "streamkey" at the start before the first dot (there
#   has to be a dot!) and the "target" at the very end, after the last '@'.
# Required: ffmpeg coreutils(tail rm)

_=$(readlink -f -- "${BASH_SOURCE:-$0}") repopath=${_%/*}
log=$repopath/process.log
in=$repopath/uploadpage/streams/$1.mp4 key=${1%%.*} target=${1##*@}
case $target in
Facebook) rtmp=rtmps://live-api-s.facebook.com:443/rtmp/$key ;;
YouTube) rtmp=rtmp://a.rtmp.youtube.com/live2/$key ;;
RestreamSG) rtmp=rtmp://singapore.restream.io/live/$key ;;
*) rtmp=rtmp://live.restream.io/live/$key
esac

set -o pipefail  # to get ffmpeg's returncode
! ffmpeg -re -y -i $in -c:v copy -c:a copy -f flv "$rtmp" |tail -n 20 >"$in.log" &&
	echo "Error while streaming $1" >>"$log" ||
	rm "$in.log"  # Remove tailfile if no errors
